# Non-mod-specific properties
modLoader       = "javafml"
loaderVersion   = "[1,)"
license         = "MIT"
showAsResourcePack = false
showAsDataPack  = false

# Your mod’s entry
[[mods]]
modId           = "dimensionalpha"
version         = "1.0.0"
displayName     = "Dimension Alpha Teleporter"
description     = '''
Adds a simple teleportation block that shuttles you between the Overworld
and your custom Dimension Alpha.
'''
authors         = "Envy Games"
